### ISSUE TITLE
H&E staining images in Fig 4

### ISSUE THREAD

**Issue by JunMa11** [buenrostrolab/slide_dna_seq_analysis#1]
Thanks for sharing this awesome work!

Could you please share the original H&E staining images that were used in the paper?

**Comment by zchiang** [comment]
Thanks for your interest in our paper!

We've uploaded the H&Es here:  https://www.dropbox.com/sh/7ruurqqo5hzrxv7/AACXt0EiuBPEEqzMsNd8W28na?dl=0

Let me know if you have any issues accessing them!

**Comment by shashwatsahay** [comment]
Hi @zchiang could you please reupload this the link is broken

**Comment by zchiang** [comment]
Hi @shashwatsahay, the H&Es have been re-uploaded here:

https://drive.google.com/drive/folders/1X6gXMxBIyJzLcAnR-MhNvIytcyaDQLqH?usp=drive_link

Let me know if you have any issues.

**Comment by shashwatsahay** [comment]
Hey @zchiang 

Do you have the H&E for the fig3 also?

I think the one above is only for fig4...

Sorry for the confusion
