### ISSUE TITLE
slide-seq-RNA sequencing library structure and processing suggestions

### ISSUE THREAD

**Issue by ruqianl** [buenrostrolab/slide_dna_seq_analysis#4]
Hi @zchiang ,

Thanks for sharing the datasets! 

I'm currently trying to reproduce the analysis in the paper on the slide-RNAseq mouse cancer dataset. I got the sparse gene expression matrix downloaded from the SingleCell Portal (mouse_liver_met_2_rna_201002_04.sparse_expression.txt), but was wondering what is the recommended process for generating this output.

I understand the https://github.com/MacoskoLab/slideseq-tools was applied to generate the results in this paper, however, it does not look very readily usable (or not yet?) to external users (external to Broad)? Or starting with the splitted fastqs like:

SRR16220119_1.fastq
```
@SRR16220119.1 1 length=44
NGAGTAAATCTTCAGCGTTCCCGAGAGAAAACATCCTCATATTT
+SRR16220119.1 1 length=44
#::FFFFFFFFFFFFFFFFFFFFFFFF:FF:FFFFFFFF:FFFF
@SRR16220119.2 2 length=44
NCACAGAGTCTTCAGCGTTCCCGAGAACGAATGTCAGTACTATT
+SRR16220119.2 2 length=44
#FFFFFFFF:FFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
@SRR16220119.3 3 length=43
NCGATTTGTCTTCAGCGTTCCCTCTGAGACATGTGCACATTAC

```
SRR16220119_2.fastq

```
@SRR16220119.1 1 length=56
ATGAGAAGGATATTGATGCCTACAGAGCTAAAGTAAAACCTGATGCAGCGAAAAAG
+SRR16220119.1 1 length=56
FFF:,:,F:FFFF:,,F,:,F:FFFFF,F,F,:,FFF,,,F,FFF,FFF,FFFF,,
@SRR16220119.2 2 length=55
GTGAAGGGGGGAGCTGGCTGGAGAGACATTTGAAGCCACTCTGGTTCTTAGATCA
+SRR16220119.2 2 length=55
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFF
@SRR16220119.3 3 length=56
GTGTGTGTGTCTGTGTGTGTGTGTGTGTGAGAGAGAGAGAGAGAGAGAGAGAGAGA
+SRR16220119.3 3 length=56
FFFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
```

- Would it be appropriate to use the pre-processing steps as in the https://github.com/buenrostrolab/slide_dna_seq_analysis/blob/main/scripts/run/slidedna_alignment_template.sh (Step 2 to Step4) and then use STAR to generate the alignment file/count matrix? 
- Could you specify the sequencing library structures please eg barcode, UMI , cDNA positions, and adapter sequences?

Thank you very much
Ruqian

**Comment by zchiang** [comment]
Hi @ruqianl,

The slidedna_alignment_template.sh script is specific to slide-DNA data and would not be appropriate for the RNA. Would you be able to move this issue to the general Slide-seq tools repository that you linked? James who maintains that repo should be to answer your questions. Sorry for the inconvenience!

Zack
