### ISSUE TITLE
incorrect description of human_genes.txt?

### ISSUE THREAD

**Issue by gancao** [buenrostrolab/slide_dna_seq_analysis#5]
The website (https://singlecell.broadinstitute.org/single_cell/study/SCP1278/spatial-genomics-enables-multi-modal-study-of-clonal-heterogeneity-in-tissues#study-download) shows that human_genes.txt : "List of genes in hg19, corresponds to the second column of slide-RNA-seq sparse expression matrices". But the the second column of slide-RNA-seq sparse expression matrices means bead indexes and the first column means the gene indexes corresponding to the human_genes.txt. 

Do I understand correctly?

**Comment by zchiang** [comment]
Hi @gancao,

Thanks for pointing this out! You are correct that the first column goes from 1-26001, corresponding to the number of genes in human_genes.txt, while the second column goes from 1-34263, corresponding to the number of beads in this array.

I've fixed the descriptions for both the mouse and human data in the Broad single cell portal. Please let me know if you encounter any other issues, and thanks again!
