### ISSUE TITLE
Full list of bead coordinates

### ISSUE THREAD

**Issue by shashwatsahay** [buenrostrolab/slide_dna_seq_analysis#7]
Hey 

When we run the bam file of human_colon_cancer_3_dna through umitools group command the file outputs the run.group.tsv

On running a simple script ` cut -f 7 run.group.tsv|sort|uniq|wc -l` provides us the output of 145423, which I think is the total number of beads that were there on the slide, is this assumption correct?

If so when we look at the coordinate file as provided here 

https://github.com/buenrostrolab/slide_dna_seq_analysis/blob/main/data/human_colon_cancer_3_dna/human_colon_cancer_3_dna_191204_19.bead_locations.csv

We only see a total number of beads which is equal to 41181.  Is the coordinate file you shared filtered in anyway, if so could you please provide us with an unfiltered version of the file. Or a set of unfiltered list barcodes which were used for the experiments.

Thanks

**Comment by shashwatsahay** [comment]
Hi @zchiang 

Just bumping this in case it was missed

**Comment by zchiang** [comment]
Hi Shashwat,

Thanks for your patience, this was quite tricky to figure out, as I'm no longer working on it anymore.

You are correct that the 41,181 barcodes provided is a filtered set. However, the number probably isn't as high as 145,423, as this number potentially includes sequencing errors, index swapping between samples, free floating beads in solution, etc.

Based on our estimates, there are probably ~80k barcodes per slide. However, this list will also not be without errors, as it is the result of our in situ sequencing pipeline. In converting microscopy images to hard called bases, we are obscuring information about imperfect bead synthesis, incomplete enzymatic sequencing reactions, microscope bias, etc.

I have attached paired lists of unfiltered barcodes and locations for human_colon_cancer_3_dna as requested.
[BeadLocations.txt](https://github.com/buenrostrolab/slide_dna_seq_analysis/files/12516580/BeadLocations.txt)
[BeadBarcodes.txt](https://github.com/buenrostrolab/slide_dna_seq_analysis/files/12516581/BeadBarcodes.txt)
 Please let me know if there's anything else I can answer.

Zack

**Comment by shashwatsahay** [comment]
HI @zchiang 

Thank you for the data, could you provide this for all the samples please.

**Comment by shashwatsahay** [comment]
@zchiang  Also I think the formating of the bead location is a bit off with only 2 line in it

**Comment by zchiang** [comment]
Hi, sorry for the delay -- I sent a message to my co-authors several weeks ago, but the request to retrieve the files from their institute's long term file storage was lost somewhere. Will follow up and report back.

**Comment by zchiang** [comment]
Also, just in case you were still having trouble with the bead locations file, the locations are comma separated.

**Comment by shashwatsahay** [comment]
Yeah I figured that out!!!
Thanks
